# Generated by Django 3.1.1 on 2020-09-29 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='code',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='小区编码'),
        ),
    ]
